config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  # get 'team', to: 'static_pages#team'
  # get 'contact', to: 'static_pages#contact'
  resources :teams, only: [:index]
  resources :contacts, only: [:index]


  root 'static_pages#index'

  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
   end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

	belongs_to :user
	has_many :comments
	has_many :likes
  has_many :users, through: :likes, dependent: :destroy
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("le %m/%d/%y à %l:%M %p")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token

	belongs_to :city
  has_many :comments
  has_many :likes, dependent: :destroy
	has_many :gossips
  has_many :messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
  validates :password, presence: true, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
      before_action :authenticate_user, only: [:new, :create, :destroy]
      before_action :find_gossip
      before_action :find_like, only: [:destroy]

  def new
  end

  def create
    if already_liked?
        flash[:notice] = "You can't like more than once"
    else
      @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
      flash[:notice] = "Like ajouté !"
    end
    redirect_to gossip_path(params[:gossip_id])

  end

  def destroy
    if !(already_liked?)
        flash[:notice] = "Cannot unlike"
      else
        @like.destroy
        flash[:danger] = "Like enlevé !"
      end
    redirect_to gossip_path(params[:gossip_id])
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end

  def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
    end
  end

  def find_gossip
      @gossip = Gossip.find(params[:gossip_id])
  end

  def find_like
     @like = @gossip.likes.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
    # @gossip = Gossip.all.order('created_at DESC')
    # affichage des derniers gossips
    @gossip = Gossip.all.last(9).reverse
    @gossip_number = Gossip.all.count
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    puts "*" * 60
    puts params
    puts "*" * 60
    @user = User.new(first_name: params[:first_name],
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city_id: City.all.sample.id)

    if @user.save 
      log_in(@user)
      redirect_to root_path, :notice => "Bienvenue #{@user.first_name} !"
    else
      render 'new'
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/static_pages/index.html.erb
<% if flash.now[:notice] %>
<div class="alert alert-success">
  <div class="notice">
    <%= flash.now[:notice] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% elsif flash.now[:danger] %>
<div class="alert alert-danger">
  <div class="danger">
    <%= flash.now[:danger] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>
<div class="jumbotron mr-2">
  <img class="rounded float-right img-thumbnail img-fluid m-2" src="http://a51.idata.over-blog.com/500x247/1/30/71/79/Septembre-2010/novembre-2010/Felix-Potin-influence.JPG" alt="potin">
  <h1 class="display-4">Bienvenue sur Secretssip</h1>
  <p class="lead">Là où rien ne peux être dissimuler..</p>
  <hr class="my-4">
  <% if session[:user_id] != nil %>
    <p>Nous avons <span class="text-monospace font-weight-bold"><%= @gossip_number %></span> secrets, mets y ta touche personnelle :</p>
    <%= link_to "Ajouter un potin", new_gossip_path,:class => "btn-danger btn btn-lg"%>
  <% else %>
    <p>Nous avons <span class="text-monospace font-weight-bold"><%= @gossip_number %></span> secrets, inscris-toi pour dévoiler des secrets :</p>
    <%= link_to "Je m'inscris", new_user_path,:class => "btn-danger btn btn-lg"%>
  <% end %>
</div>

<!-- affichage des derniers gossips -->
<h2 class="text-center m-5"><i class="fas fa-comments"></i> Les derniers secrets : </h2>
<div class="card-columns border-info container ">
  <% @gossip.each do |i| %>
      <div class="card">
        <div class="card-header pb-1 d-flex">
          <h5 class="card-title"><%= i.title %></h5>
          <div class="ml-auto">
            <span class="badge badge-secondary"><i class="fas fa-comments"></i> <%= i.comments.count %></span>
            <span class="badge badge-secondary"><i class="fas fa-heart"></i> <%= i.likes.count %></span>
          </div>
        </div>
        <div class="card-body text-center">
          <p class="card-subtitle mb-2 text-info">" <%= i.content %> "</p>
          <p class="card-subtitle mb-2 text-muted"><em>de <%= i.user.first_name %></em></p>
          <%= link_to "Go Potin", gossip_path(i.id),:class => "btn-info btn p-1"%>
        </div>
      </div>
  <% end %>
</div>

<p class="text-center m-3"><%= link_to "Voir tout les secrets (#{@gossip_number})", gossips_path, class:"btn btn-danger btn-lg" %></p>