config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  # get 'team', to: 'static_pages#team'
  # get 'contact', to: 'static_pages#contact'
  resources :teams, only: [:index]
  resources :contacts, only: [:index]


  root 'static_pages#index'

  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token

	belongs_to :city
  has_many :comments
  has_many :likes, dependent: :destroy
	has_many :gossips
  has_many :messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
  validates :password, presence: true, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    puts "*" * 60
    puts params
    puts "*" * 60
    @user = User.new(first_name: params[:first_name],
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city_id: City.all.sample.id)

    if @user.save 
      log_in(@user)
      redirect_to root_path, :notice => "Bienvenue #{@user.first_name} !"
    else
      render 'new'
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Créer son compte</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>

    <div class="card-body text-info">
      <div class="form-group">
        <%= text_field_tag 'first_name', '', class: "form-control", placeholder: "Prénom" %>
        <%= text_field_tag 'last_name', '', class: "form-control", placeholder: "Nom" %>
        <%= text_field_tag 'description', '', class: "form-control", placeholder: "Description" %>
        <%= text_field_tag 'age', '', class: "form-control", placeholder: "Âge" %>
        <%= text_field_tag 'email', '', class: "form-control", placeholder: "Email" %>
        <%= password_field_tag 'password', '', class: "form-control", placeholder: "Mot de passe" %>
        <br /> <br />
        <%= submit_tag "Je m'inscris !", class: "btn btn-info" %>
        <p class="mt-4">Déjà un compte ? <%= link_to "Je me connecte !", new_session_path %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="card border-info m-5 text-center">
  <div class="card-header">
    <h1><i class="fas fa-user"></i> <u><%= @user.first_name + " " + @user.last_name  %></u></h1>
  </div>
  <div class="card-body text-info">
    <ul class="card-text list-group">
      <li class="list-group-item">Prénom : <%= @user.first_name %></li>
      <li class="list-group-item">Nom : <%= @user.last_name %></li>
      <li class="list-group-item">Description : <%= @user.description %></li>
      <li class="list-group-item">Email : <%= @user.email %></li>
      <li class="list-group-item">Âge : <%= @user.age %></li>
      <li class="list-group-item">Ville : <%= link_to @user.city.name , city_path(@user.city.id),:class => ""%></li>
    </ul>
  </div>
  <div>
    <% if @user.id != current_user.id %>
      <%= link_to "<i class='fas fa-envelope'></i> ".html_safe + " Envoyer un message à #{@user.first_name}", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class:"btn-info btn m-2" %>
    <% end %>
  </div>
</div>

<!-- affichage des potins -->
<h2 class="text-center mb-5"><i class="far fa-newspaper"></i> Potins de <%= @user.first_name %> </h2>
<div class="card-columns border-info container">
  <% @user.gossips.each do |i| %>
    <div class="card">
      <div class="card-header pb-1 d-flex">
        <h5 class="card-title"><%= i.title %></h5>
        <div class="ml-auto">
          <span class="badge badge-secondary"><i class="fas fa-comments"></i> <%= i.comments.count %></span>
          <span class="badge badge-secondary"><i class="fas fa-heart"></i> <%= i.likes.count %></span>
        </div>
      </div>
      <div class="card-body text-center">
        <h6 class="card-subtitle mb-2 text-muted">" <%= i.content %> "</h6>
        <%= link_to "Go Potin", gossip_path(i.id),:class => "btn-info btn p-1"%>
      </div>
    </div>
  <% end %>
</div>
<hr>

<!-- affichage des potins likés-->
<% if @user.likes.count > 0 %>
  <h2 class="text-center mb-5"><i class="fas fa-heart"></i> Potins likés </h2>
  <div class="card-columns border-info container">
    <% @user.likes.each do |i| %>
      <div class="card">
        <div class="card-header pb-1 d-flex">
          <h5 class="card-title"><%= i.gossip.title %></h5>
          <div class="ml-auto">
            <span class="badge badge-secondary"><i class="fas fa-comments"></i> <%= i.gossip.comments.count %></span>
            <span class="badge badge-secondary"><i class="fas fa-heart"></i> <%= i.gossip.likes.count %></span>
          </div>
        </div>
        <div class="card-body text-center">
          <h6 class="card-subtitle mb-2 text-muted">" <%= i.gossip.content %> "</h6>
          <%= link_to "Go Potin", gossip_path(i.gossip.id),:class => "btn-info btn p-1"%>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
<% end %>

<!-- affichage des commentaires-->
<% if @user.comments.count > 0 %>
  <h2 class="text-center mb-5"><i class="far fa-comments"></i> Commentaires </h2>
  <div class="card-columns border-info container">
    <% @user.comments.each do |i| %>
      <div class="card">
        <div class="card-body text-center">
          <h6 class="card-subtitle mb-2 text-muted">" <%= i.content %> "</h6>
          <%= link_to "Go Potin", gossip_path(i.gossip.id),:class => "btn-info btn p-1"%>
        </div>
      </div>
    <% end %>
  </div>
<% end %>