config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  # get 'team', to: 'static_pages#team'
  # get 'contact', to: 'static_pages#contact'
  resources :teams, only: [:index]
  resources :contacts, only: [:index]


  root 'static_pages#index'

  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

	belongs_to :user
	has_many :comments
	has_many :likes
  has_many :users, through: :likes, dependent: :destroy
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new]
  before_action :author_gossip, only: [:edit, :update, :destroy]

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossips = Gossip.all.reverse
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = @gossip.user
    @comments = @gossip.comments
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @gossip = Gossip.new
    @user_id = session[:user_id]
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id] )

    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to root_path, :notice => "Potin créé !"
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)

      if @gossip.update(gossip_params)
        # flash[:notice] = "Gossip mis à jour"
        redirect_to @gossip, :notice => "Gossip mis à jour"
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
        flash[:danger] = "Connecte-toi ;)"
        redirect_to new_session_path
    end
  end

  def author_gossip
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user || current_user.id == 26
        flash[:danger] = "Tu n'es pas l'auteur de ce potin."
        redirect_to root_path
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<div class="card border-info m-5">
 <div class="card-header"><h1><i class="fas fa-edit"></i> Édite le potin n° <%= params[:id] %></h1></div>

  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= label_tag 'Titre'%>
          <%= text_field_tag :title, @gossip.title, class:'form-control', placeholder: @gossip.title %>
          <br /> <br />

          <%= label_tag 'Contenu du potin' %>
          <%= text_area_tag :content, @gossip.content, class:'form-control', placeholder: @gossip.content %>
          <br /> <br />

          <%= submit_tag "Éditer le potin", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>


  </div>
</div>

<% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
      <% end %>

app/views/gossips/index.html.erb
<% if flash.now[:notice] %>
<div class="alert alert-success">
  <div class="notice">
    <%= flash.now[:notice] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>

  <h1 class="text-center m-4"><i class="fas fa-comments"></i> Tous les potins</h1>

<!-- affichage des gossips -->
  <div class="card-columns border-info container ">
  <% @gossips.each do |i| %>
    <div class="card">
      <div class="card-header pb-1 d-flex">
        <h5 class="card-title"><%= i.title %></h5>
        <div class="ml-auto">
          <span class="badge badge-secondary"><i class="fas fa-comments"></i> <%= i.comments.count %></span>
          <span class="badge badge-secondary"><i class="fas fa-heart"></i> <%= i.likes.count %></span>
        </div>

      </div>
      <div class="card-body text-center">
        <p class="card-subtitle mb-2 text-info">" <%= i.content %> "</p>
        <p class="card-subtitle mb-2 text-muted"><em>de <%= i.user.first_name %></em></p>
        <%= link_to "Go Potin", gossip_path(i.id),:class => "btn-info btn p-1"%>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Ajouter un potin</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= text_field_tag 'title', @gossip.title, class: "form-control", placeholder: "Le titre de ton potin" %>
          <%= text_area_tag 'content', @gossip.content, class: "form-control", placeholder: "Ton potin" %>
          <br /> <br />

          <%= submit_tag "Ajouter mon potin", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>
</div>
    <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
      <% end %>

app/views/gossips/show.html.erb
<% if flash.now[:notice] %>
<div class="alert alert-success">
  <div class="notice">
    <%= flash.now[:notice] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>
<% if flash.now[:danger] %>
<div class="alert alert-success">
  <div class="danger">
    <%= flash.now[:danger] %>
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>
<!-- affichage GOSSIP -->
<div class="card border-info text-center m-5">

  <div class="card-header">
    <p class="text-right text-muted">
      <i class="fas fa-edit"></i> <%= link_to "Éditer le potin", edit_gossip_path(params[:id]) %>&nbsp;&nbsp;
      <i class="fas fa-trash-alt"></i> <%= link_to "Supprimer le potin", gossip_path(params[:id]), type: "submit", method: "delete", data: { confirm: "Tu es sûr-e ?" }  %>
    </p>
    <h1><i class="far fa-newspaper"></i> <u><%= @gossip.title %></u> <small class="text-muted">(Potin n° <%= params[:id] %>)</small></h1>
  </div>
  <div class="card-body text-info">
    <blockquote class="blockquote">
      <p class="m-2"><%= @gossip.content %></p>
        <footer class="blockquote-footer">
          <cite title="Auteur du potin">
            <%= link_to @gossip.user.first_name + " " + @gossip.user.last_name, user_path(@user.id) %>
          </cite>
          de la ville de <%= @gossip.user.city.name %>
        </footer>
      </blockquote>
<!-- bouton like (seulement si on est connecté) -->
      <% if session[:user_id] != nil %>
        <% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <%= link_to '<i class="far fa-heart"></i> Unlike'.html_safe, gossip_like_path(params[:id], pre_like), method: :delete, :class => "btn-danger btn p-1"  %>
        <% else %>
          <%= link_to '<i class="fas fa-heart"></i> Like'.html_safe, gossip_likes_path(params[:id]), method: :post, :class => "btn-info btn p-1" %>
        <% end %>
      <% end %>
  </div>

<!-- affichage likes et date de création -->
  <div class="card-footer d-flex">
    <div class="text-info">
      <i class="fas fa-heart"></i> <%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? ' Like' : ' Likes'%> :
        <span class="text-muted">
          <% @gossip.likes.each do |l| %>
            <%= link_to '<i class="fas fa-user fa-xs"></i> '.html_safe + l.user.first_name, user_path(l.user.id), class:"badge badge-pill badge-info" %>
          <% end %>
        </span>
    </div>
    <div class="text-muted ml-auto mt-2 mt-lg-0 "><i class="far fa-clock"></i> <%= @gossip.created_at %></div>
  </div>
</div>

<!-- Ajouter un commentaire (seulement si on est connecté) -->
<% if session[:user_id] != nil %>
  <div class="card m-5">
   <div class="card-header">
    <h2>Ajouter un commentaire</h2>
    </div>
    <%= form_tag(gossip_comments_path(params[:id]), method: :create) do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= label_tag 'Contenu du commentaire' %>
          <%= text_area_tag 'content', @comment.content, class: "form-control", placeholder: "Ton commentaire" %>
          <br /> <br />
          <%= submit_tag "Ajouter un commentaire", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<!-- Affichage des commentaires -->
<% if @comments.count > 0 %>
  <h1 class="text-center m-4"><i class="far fa-comments"></i> Tous les commentaires</h1>
    <div class="card-columns border-info container">
      <% @comments.each do |c| %>
        <div class="card">
          <div class="card-body">
          <h5 class="card-title"><i class="far fa-comment"></i> <%= c.content %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><i class="far fa-user"></i> <%= c.user.first_name + " " + c.user.last_name %></h6>
            <i class="fas fa-edit"></i> <%= link_to "Éditer", edit_gossip_comment_path(@gossip.id, c.id) %>&nbsp;&nbsp;
            <i class="fas fa-trash-alt"></i> <%= link_to "Supprimer", gossip_comment_path(@gossip.id, c.id), type: "submit", method: "delete", data: { confirm: "Tu es sûr-e ?" }  %>
          </div>
        </div>
      <% end %>
    </div>
<% end %>