config/routes.rb
Rails.application.routes.draw do
  #static pages
  get 'welcome/:user_entry', to: 'welcome#show'
  # get 'team', to: 'static_pages#team'
  # get 'contact', to: 'static_pages#contact'
  resources :teams, only: [:index]
  resources :contacts, only: [:index]


  root 'static_pages#index'

  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
   end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

	belongs_to :user
	has_many :comments
	has_many :likes
  has_many :users, through: :likes, dependent: :destroy
	has_many :gossips_tags
	has_many :tags, through: :gossips_tags

end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("le %m/%d/%y à %l:%M %p")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips_tags
	has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token

	belongs_to :city
  has_many :comments
  has_many :likes, dependent: :destroy
	has_many :gossips
  has_many :messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email address please" }
  validates :password, presence: true, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
      before_action :authenticate_user, only: [:new, :create, :destroy]
      before_action :find_gossip
      before_action :find_like, only: [:destroy]

  def new
  end

  def create
    if already_liked?
        flash[:notice] = "You can't like more than once"
    else
      @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
      flash[:notice] = "Like ajouté !"
    end
    redirect_to gossip_path(params[:gossip_id])

  end

  def destroy
    if !(already_liked?)
        flash[:notice] = "Cannot unlike"
      else
        @like.destroy
        flash[:danger] = "Like enlevé !"
      end
    redirect_to gossip_path(params[:gossip_id])
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end

  def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
    end
  end

  def find_gossip
      @gossip = Gossip.find(params[:gossip_id])
  end

  def find_like
     @like = @gossip.likes.find(params[:id])
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secretssip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- css bootstrap -->
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"> -->
    <link href="https://bootswatch.com/4/lux/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Projet", root_path, :class => "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav navbar-nav-scroll">
          <%= link_to "Home", root_path, :class => "nav-item nav-link" %>
          <%= link_to "Contact", contacts_path, :class => "nav-item nav-link" %>
          <%= link_to "Team", teams_path, :class => "nav-item nav-link" %>
          <%= link_to "Secret au hasard", gossip_path(Gossip.all.sample.id), :class => "nav-item nav-link" %>
          <% if session[:user_id] != nil %>
            <%= link_to "Ajouter un secret", new_gossip_path, :class => "nav-item nav-link" %>
          <% end %>
        </div>
<!-- partie droite avec dropdown -->
        <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">

          <% if session[:user_id] != nil %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name %>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Profil", user_path(session[:user_id]), :class => "dropdown-item" %>
                <% count_messages = 0 %>
                <% current_user.messages.each do |m| %>
                  <% count_messages += 1 if m.read? %>
                <% end %>
                <% if count_messages > 0 %>
                  <%= link_to 'Messagerie', conversations_path, class:'dropdown-item' %><span class="badge badge-danger">new</span>
                <% end %>
                <%= link_to 'Messagerie', conversations_path, class:'dropdown-item' %>
                <%= link_to "Se déconnecter", session_path(session[:user_id]), method: :delete, data: { confirm: "Tu es sûr-e ?" }, :class => "dropdown-item" %>
              </div>
            </div>

          <% else %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Connexion / Inscription
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Se connecter", new_session_path, :class => "dropdown-item" %>
                <%= link_to "S'inscrire", new_user_path, :class => "dropdown-item" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

  <div class="ml-2 mt-2" >
    <%= yield %>
  </div>

  <footer class="text-muted p-3 mt-4 text-center w-100 ">
    Made with <i class="fas fa-heart"></i> à Caen
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
    $(".dropdown-toggle").dropdown();
  })
</script>
  </body>
</html>